### ISSUE TITLE
Improvements on data about the contacts

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/ureport#855]
Hi everyone, after talking with some UReport customers they raise the necessity for more information about gender and skin color for contacts for each workspace.

**Gender:** actually the information on UReport is generic including the 3 options (male, female, and not declared). The users talked that some contacts didn't respond to the question about gender because the two options are not representative for some contacts.

**Skin color:** This information can be interesting on UReport, in some countries this data is very important to collect and make available the polls on the workspace, and with this working on social impact causes with these data.

I open this issue for us to discuss to get your feedback about this, and after this discuss how can be added to the UReport project.
Thanks.

**Comment by ericnewcomer** [comment]
Pretty sure gender has a non-binary option already and can be enabled on a per-country basis. The skin color request is making my skin crawl.

**Comment by ericnewcomer** [comment]
@matmsa27 any reason you chose to close this?

**Comment by matmsa27** [comment]
Hi Eric, after your first negative reply and some feedbacks that we received, we reflect that GitHub isn't the better place to discuss this, so I closed this issue, for now, to treat this in a channel more appropriate.

**Comment by ericnewcomer** [comment]
Sorry, not trying to be negative, just trying to be sensitive. Obviously demographics around things like gender and skin color are things we should be careful about baking into any product. I'm not concerned about having that discussion out in the open. I would be curious to hear what feedback you received.

All that saied, I'd move to reposition this discussion to perhaps be around split data for arbitrary demographics instead of focusing specifically on skin color, etc.
